services:
  dev-environment:
    build:
      dockerfile: Dockerfile
      target: development
    image: mlops-project-2-dev-environment
    volumes:
      - .:/pytorch-project
    env_file: ".env"
  train-model:
    build:
      dockerfile: Dockerfile
      target: train-model
    image: mlops-project-2-train-model
    volumes:
      - .:/pytorch-project
    env_file: ".env"
