services:
  dev-environment:
    build:
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/pytorch-project
    env_file: ".env"
  train-model:
    build:
      dockerfile: Dockerfile
      target: train-model
    volumes:
      - .:/pytorch-project
    env_file: ".env"
